version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*os.File).Close
        - (io.ReadCloser).Close
        - fmt.Fprintf
        - (mime/multipart.File).Close
