// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package db

import (
	"context"
	"database/sql"
)

const deleteMediaByLibrary = `-- name: DeleteMediaByLibrary :exec
DELETE FROM media WHERE library_id = ?
`

func (q *Queries) DeleteMediaByLibrary(ctx context.Context, libraryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMediaByLibrary, libraryID)
	return err
}

const deleteMediaByRatingKey = `-- name: DeleteMediaByRatingKey :exec
DELETE FROM media WHERE rating_key = ?
`

func (q *Queries) DeleteMediaByRatingKey(ctx context.Context, ratingKey string) error {
	_, err := q.db.ExecContext(ctx, deleteMediaByRatingKey, ratingKey)
	return err
}

const getMediaByRatingKey = `-- name: GetMediaByRatingKey :one
SELECT id, library_id, rating_key, title, type, year, season_number, thumb, added_at, created_at, updated_at
FROM media
WHERE rating_key = ?
`

type GetMediaByRatingKeyRow struct {
	ID           int64
	LibraryID    int64
	RatingKey    string
	Title        string
	Type         string
	Year         sql.NullInt64
	SeasonNumber sql.NullInt64
	Thumb        sql.NullString
	AddedAt      sql.NullInt64
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) GetMediaByRatingKey(ctx context.Context, ratingKey string) (GetMediaByRatingKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getMediaByRatingKey, ratingKey)
	var i GetMediaByRatingKeyRow
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.RatingKey,
		&i.Title,
		&i.Type,
		&i.Year,
		&i.SeasonNumber,
		&i.Thumb,
		&i.AddedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMedia = `-- name: ListMedia :many
SELECT id, library_id, rating_key, title, type, year, season_number, thumb, added_at, created_at
FROM media
ORDER BY added_at DESC NULLS LAST
`

type ListMediaRow struct {
	ID           int64
	LibraryID    int64
	RatingKey    string
	Title        string
	Type         string
	Year         sql.NullInt64
	SeasonNumber sql.NullInt64
	Thumb        sql.NullString
	AddedAt      sql.NullInt64
	CreatedAt    int64
}

func (q *Queries) ListMedia(ctx context.Context) ([]ListMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, listMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMediaRow
	for rows.Next() {
		var i ListMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.RatingKey,
			&i.Title,
			&i.Type,
			&i.Year,
			&i.SeasonNumber,
			&i.Thumb,
			&i.AddedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatingKeysByLibraryIDAndType = `-- name: ListRatingKeysByLibraryIDAndType :many
SELECT rating_key FROM media WHERE library_id = ? AND type = ?
`

type ListRatingKeysByLibraryIDAndTypeParams struct {
	LibraryID int64
	Type      string
}

func (q *Queries) ListRatingKeysByLibraryIDAndType(ctx context.Context, arg ListRatingKeysByLibraryIDAndTypeParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRatingKeysByLibraryIDAndType, arg.LibraryID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var rating_key string
		if err := rows.Scan(&rating_key); err != nil {
			return nil, err
		}
		items = append(items, rating_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLibrary = `-- name: UpsertLibrary :one
INSERT INTO libraries (section_key, title, type, imported_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (section_key) DO UPDATE SET
    title       = excluded.title,
    type        = excluded.type,
    imported_at = excluded.imported_at
RETURNING id, section_key, title, type, imported_at
`

type UpsertLibraryParams struct {
	SectionKey string
	Title      string
	Type       string
	ImportedAt int64
}

func (q *Queries) UpsertLibrary(ctx context.Context, arg UpsertLibraryParams) (Library, error) {
	row := q.db.QueryRowContext(ctx, upsertLibrary,
		arg.SectionKey,
		arg.Title,
		arg.Type,
		arg.ImportedAt,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.SectionKey,
		&i.Title,
		&i.Type,
		&i.ImportedAt,
	)
	return i, err
}

const upsertMedia = `-- name: UpsertMedia :exec
INSERT INTO media (library_id, rating_key, title, type, year, season_number, thumb, added_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (rating_key) DO UPDATE SET
    title         = excluded.title,
    type          = excluded.type,
    year          = excluded.year,
    season_number = excluded.season_number,
    thumb         = excluded.thumb,
    added_at      = excluded.added_at,
    updated_at    = excluded.updated_at
`

type UpsertMediaParams struct {
	LibraryID    int64
	RatingKey    string
	Title        string
	Type         string
	Year         sql.NullInt64
	SeasonNumber sql.NullInt64
	Thumb        sql.NullString
	AddedAt      sql.NullInt64
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) UpsertMedia(ctx context.Context, arg UpsertMediaParams) error {
	_, err := q.db.ExecContext(ctx, upsertMedia,
		arg.LibraryID,
		arg.RatingKey,
		arg.Title,
		arg.Type,
		arg.Year,
		arg.SeasonNumber,
		arg.Thumb,
		arg.AddedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
