// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type LibrarySetting struct {
	SectionKey string
	Enabled    int64
}

type Setting struct {
	ID       int64
	Type     string
	Key      string
	Value    sql.NullString
	Position sql.NullInt64
}
