// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Library struct {
	ID         int64
	SectionKey string
	Title      string
	Type       string
	ImportedAt int64
}

type LibrarySetting struct {
	SectionKey string
	Enabled    int64
}

type Medium struct {
	ID           int64
	LibraryID    int64
	RatingKey    string
	Title        string
	Type         string
	SeasonNumber sql.NullInt64
	Year         sql.NullInt64
	Thumb        sql.NullString
	AddedAt      sql.NullInt64
	CreatedAt    int64
	UpdatedAt    int64
}

type PosterQueue struct {
	ID        int64
	MediaID   int64
	CreatedAt int64
}

type Setting struct {
	ID       int64
	Type     string
	Key      string
	Value    sql.NullString
	Position sql.NullInt64
}
