// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: libraries.sql

package db

import (
	"context"
)

const listLibrarySettings = `-- name: ListLibrarySettings :many
SELECT section_key, enabled FROM library_settings WHERE provider = ?
`

type ListLibrarySettingsRow struct {
	SectionKey string
	Enabled    int64
}

func (q *Queries) ListLibrarySettings(ctx context.Context, provider string) ([]ListLibrarySettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLibrarySettings, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLibrarySettingsRow
	for rows.Next() {
		var i ListLibrarySettingsRow
		if err := rows.Scan(&i.SectionKey, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLibrarySetting = `-- name: UpsertLibrarySetting :exec
INSERT INTO library_settings (provider, section_key, enabled)
VALUES (?, ?, ?)
ON CONFLICT (provider, section_key) DO UPDATE SET
    enabled = excluded.enabled
`

type UpsertLibrarySettingParams struct {
	Provider   string
	SectionKey string
	Enabled    int64
}

func (q *Queries) UpsertLibrarySetting(ctx context.Context, arg UpsertLibrarySettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertLibrarySetting, arg.Provider, arg.SectionKey, arg.Enabled)
	return err
}
