// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queue.sql

package db

import (
	"context"
	"database/sql"
)

const countPosterQueue = `-- name: CountPosterQueue :one
SELECT COUNT(*) FROM poster_queue
`

func (q *Queries) CountPosterQueue(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPosterQueue)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePosterQueueByRatingKey = `-- name: DeletePosterQueueByRatingKey :exec
DELETE FROM poster_queue
WHERE media_id = (SELECT id FROM media WHERE rating_key = ?)
`

func (q *Queries) DeletePosterQueueByRatingKey(ctx context.Context, ratingKey string) error {
	_, err := q.db.ExecContext(ctx, deletePosterQueueByRatingKey, ratingKey)
	return err
}

const listPosterQueue = `-- name: ListPosterQueue :many
SELECT pq.id, m.rating_key, m.title, m.type, m.thumb
FROM poster_queue pq
JOIN media m ON m.id = pq.media_id
ORDER BY pq.created_at DESC
`

type ListPosterQueueRow struct {
	ID        int64
	RatingKey string
	Title     string
	Type      string
	Thumb     sql.NullString
}

func (q *Queries) ListPosterQueue(ctx context.Context) ([]ListPosterQueueRow, error) {
	rows, err := q.db.QueryContext(ctx, listPosterQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPosterQueueRow
	for rows.Next() {
		var i ListPosterQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.RatingKey,
			&i.Title,
			&i.Type,
			&i.Thumb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosterQueueWithMedia = `-- name: ListPosterQueueWithMedia :many
SELECT pq.id, m.id AS media_id, m.rating_key, m.title, m.type, m.season_number, m.thumb
FROM poster_queue pq
JOIN media m ON m.id = pq.media_id
ORDER BY pq.created_at DESC
`

type ListPosterQueueWithMediaRow struct {
	ID           int64
	MediaID      int64
	RatingKey    string
	Title        string
	Type         string
	SeasonNumber sql.NullInt64
	Thumb        sql.NullString
}

func (q *Queries) ListPosterQueueWithMedia(ctx context.Context) ([]ListPosterQueueWithMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, listPosterQueueWithMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPosterQueueWithMediaRow
	for rows.Next() {
		var i ListPosterQueueWithMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.RatingKey,
			&i.Title,
			&i.Type,
			&i.SeasonNumber,
			&i.Thumb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPosterQueue = `-- name: UpsertPosterQueue :exec
INSERT INTO poster_queue (media_id, created_at)
VALUES (?, ?)
ON CONFLICT (media_id) DO UPDATE SET created_at = excluded.created_at
`

type UpsertPosterQueueParams struct {
	MediaID   int64
	CreatedAt int64
}

func (q *Queries) UpsertPosterQueue(ctx context.Context, arg UpsertPosterQueueParams) error {
	_, err := q.db.ExecContext(ctx, upsertPosterQueue, arg.MediaID, arg.CreatedAt)
	return err
}
