// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
	"database/sql"
)

const getSetting = `-- name: GetSetting :one
SELECT id, type, "key", value, position FROM settings WHERE type = ? AND key = ?
`

type GetSettingParams struct {
	Type string
	Key  string
}

func (q *Queries) GetSetting(ctx context.Context, arg GetSettingParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, arg.Type, arg.Key)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Key,
		&i.Value,
		&i.Position,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT id, type, "key", value, position FROM settings ORDER BY type, position, key
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Key,
			&i.Value,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettingsByType = `-- name: ListSettingsByType :many
SELECT id, type, "key", value, position FROM settings WHERE type = ? ORDER BY position, key
`

func (q *Queries) ListSettingsByType(ctx context.Context, type_ string) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettingsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Key,
			&i.Value,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePosterSource = `-- name: UpdatePosterSource :exec
UPDATE settings SET value = ?, position = ? WHERE type = 'poster_source' AND key = ?
`

type UpdatePosterSourceParams struct {
	Value    sql.NullString
	Position sql.NullInt64
	Key      string
}

func (q *Queries) UpdatePosterSource(ctx context.Context, arg UpdatePosterSourceParams) error {
	_, err := q.db.ExecContext(ctx, updatePosterSource, arg.Value, arg.Position, arg.Key)
	return err
}

const updateSetting = `-- name: UpdateSetting :exec
UPDATE settings SET value = ? WHERE type = ? AND key = ?
`

type UpdateSettingParams struct {
	Value sql.NullString
	Type  string
	Key   string
}

func (q *Queries) UpdateSetting(ctx context.Context, arg UpdateSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateSetting, arg.Value, arg.Type, arg.Key)
	return err
}
